#!/bin/zsh
#
# .aliases - Set whatever shell aliases you want.
#

# mask built-ins with better defaults
alias vi=vim
alias hx=helix

# more ways to ls
alias lla='ls -lah'
alias lia='ls -liah'
alias lsl='ls -lh'
alias ll='ls -lh'

# fix common typos
alias cd..='cd ..'

# tar
alias tarls="tar -tvf"
alias untar="tar -xf"

# find
alias fd='find . -type d -name'
alias ff='find . -type f -name'

# url encode/decode
alias urldecode='python3 -c "import sys, urllib.parse as ul; \
    print(ul.unquote_plus(sys.argv[1]))"'
alias urlencode='python3 -c "import sys, urllib.parse as ul; \
    print (ul.quote_plus(sys.argv[1]))"'

# misc
alias zshrc='${EDITOR:-vi} "${ZDOTDIR:-$HOME}"/.zshrc'
alias zbench='for i in {1..10}; do /usr/bin/time zsh -lic exit; done'
alias zdot='cd ${ZDOTDIR:-~}'
alias duh='du -h'
alias vernicht='kill -9'
alias vim=nvim


# git
alias gsta='git status'
alias gadd='git add'
alias gcam='git commit -am'
alias gcim="git ci -m"
alias gamendall='git commit -a --amend --no-edit'

alias ledger=hledger
alias on=xdg-open

