#!/bin/zsh

path+=("/lib/llvm-20/bin")
path+=("$HOME/.cache/scalacli/local-repo/bin/scala-cli")
path+=("$HOME/eti-bfc/bin")

zstyle ':plugins:mlir' mlir_opt_programs mlir-opt

source "$HOME/venv/bin/activate" 

function pygmentize_c() {
  if [ -t 1 ] && command -v pygmentize &> /dev/null ; then
    local stylesheet
    zstyle -s ':plugins:mlir:pygments' stylesheet stylesheet

    pygmentize -l "c" -x ${stylesheet:+-O "style=$stylesheet"} /dev/stdin
  else
    # If we're not in a term (eg we are piping to another command),
    # just passthrough.
    cat /dev/stdin > /dev/stdout
  fi
}

function bfc-opt() {
  # Wrap with colors
  if (($@[(I)-S])); then
    command bfc-opt "$@" | pygmentize_mlir
  else
    command bfc-opt "$@" | pygmentize_c
  fi
}

