#!/bin/zsh
#
# .zstyles - Set zstyle settings for plugins that need them.
#

#
# Antidote
#


zstyle ':zsh-utils:plugins:history' use-xdg-basedirs 'yes'
zstyle ':antidote:bundle' file ${ZDOTDIR:-~}/zsh_plugins.txt

zstyle ':antidote:bundle:*' zcompile 'yes'
zstyle ':antidote:bundle' use-friendly-names 'yes'
zstyle ':antidote:static' zcompile 'yes'


zstyle ':plugins:mlir:pygments' enabled 'yes'
zstyle ':plugins:mlir:pygments' lexer ''
zstyle ':plugins:mlir:pygments' stylesheet github-dark
zstyle ':plugins:mlir' mlir_opt_programs mlir-opt tilefirst-opt cinm-opt 

# zstyle ':completion::complete:tilefirst-opt:values:' insert-unambiguous no
#
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#505050"

